### ISSUE TITLE
x86_64 `unw_cursor_t` is self-referential but `Cursor` is not pinned

### ISSUE THREAD

**Issue by EliaGeretto** [sfackler/rstack#16]
For `x86_64`, `unw_cursor_t` is self-referential. This can be observed in the following line:
https://github.com/libunwind/libunwind/blob/v1.5/src/x86_64/Ginit_local.c#L52

`Cursor` contains an `unw_cursor_t`, but it is not marked as pinned. As a consequence, the reference in `dwarf.as_arg` will be invalidated on the first move. For the same reason, it should also not derive `Clone`, I believe.

I am not sure if this is a bug in `libunwind`, since they state in the documentation that:
> The former would  be  used  as  the
> current  cursor  and  prev would be maintained as the ``previous frame'' cursor by copying
> the contents of curr to prev right before calling unw_step()

This means that cursors are meant to be copiable, but the `x86_64` one is obviously not. Still, I thought it was worth reporting.

**Comment by EliaGeretto** [comment]
I have reported the issue to `libunwind` as well, this should help figuring out who is right with their assumptions: https://github.com/libunwind/libunwind/issues/233

**Comment by sfackler** [comment]
Given that the cursor is explicitly documented as copyable that seems like either a bug in libunwind, or that self referential field isn't actually used. At least in my experience, it seems like copying the cursor on x86_64 does work so I would assume it's the latter.

**Comment by EliaGeretto** [comment]
I was trying to write a PR that allows to access architecture specific registers, at least for x86_64. That is how I stumbled upon this. When doing so, the self-reference is accessed here and then used later in the same function:
https://github.com/libunwind/libunwind/blob/4c980e2b29cdb9d21cfc341abdec3a6ee46e0483/src/x86_64/Ginit.c#L345

Obviously, fun things happen since that reference points to uninitialized memory. Anyway, you are probably right, it is likely to be a bug in `libunwind`. If that is the case, though, it has been there since 2008. I guess it is better to wait and see what they say.

**Comment by EliaGeretto** [comment]
The problem was fixed in https://github.com/libunwind/libunwind/commit/debb6128d17b782552d53efa8869a392d1f40a83 for `x86_64`. The bug was upstream.

**Comment by sfackler** [comment]
Thanks!
