### ISSUE TITLE
Fails to build when linking with `lld`

### ISSUE THREAD

**Issue by Kmeakin** [sfackler/rstack#21]
The `unwind-sys` crate fails to build when using `lld` as the linker:

`RUSTFLAGS='-Clink-args=-fuse-ld=lld' cargo t --all-features` produces a linker error:

```
          ld.lld: error: /usr/lib/x86_64-linux-gnu/libunwind-ptrace.so: undefined reference to lzma_stream_buffer_decode [--no-allow-shlib-undefined]
          ld.lld: error: /usr/lib/x86_64-linux-gnu/libunwind-ptrace.so: undefined reference to lzma_index_uncompressed_size [--no-allow-shlib-undefined]
          ld.lld: error: /usr/lib/x86_64-linux-gnu/libunwind-ptrace.so: undefined reference to lzma_index_end [--no-allow-shlib-undefined]
          ld.lld: error: /usr/lib/x86_64-linux-gnu/libunwind-ptrace.so: undefined reference to lzma_index_buffer_decode [--no-allow-shlib-undefined]
          ld.lld: error: /usr/lib/x86_64-linux-gnu/libunwind-ptrace.so: undefined reference to lzma_stream_footer_decode [--no-allow-shlib-undefined]
          ld.lld: error: /usr/lib/x86_64-linux-gnu/libunwind-ptrace.so: undefined reference to lzma_index_size [--no-allow-shlib-undefined]
          collect2: error: ld returned 1 exit status
          
  = help: some `extern` functions couldn't be found; some native libraries may need to be installed or have their path specified
  = note: use the `-l` flag to specify native libraries to link
  = note: use the `cargo:rustc-link-lib` directive to specify the native libraries to link with Cargo (see https://doc.rust-lang.org/cargo/reference/build-scripts.html#cargorustc-link-libkindname)

error: could not compile `unwind-sys` due to previous error
```

Your crate seems to rely on some GNU `ld` behaviour that the `lld` team are unwilling to replicate (https://github.com/llvm/llvm-project/issues/54700). 

I suggest this can be fixed by adding a `cargo:rustc-link-lib=lzma` directive to your `build.rs` build script.

**Comment by sfackler** [comment]
The build script relies on pkg-config for its linker configuration. You should file this issue on the libunwind project (or the packager that created your libunwind binaries): https://github.com/sfackler/rstack/blob/master/unwind-sys/build.rs#L35

**Comment by Kmeakin** [comment]
`libunwind.pc` includes `-llzma` in its `Libs.private`, which is only added to the linker args if `pkg-config` is called with the `--static` flag.

The solution is to replace 
```let library = pkg_config::probe_library(lib).unwrap();```
with 
```let library = pkg_config::Config::new().statik(true).probe(lib).unwrap();``` 
in `build.rs`.

**Comment by sfackler** [comment]
But you're not statically linking to libunwind - the linker error references `libunwind-ptrace.so` which is a dynamic library.

**Comment by cameron-martin** [comment]
Looks like this is the problem: https://github.com/libunwind/libunwind/issues/586

However, libunwind is still on 1.6.2 on Ubuntu 22.04.

Would you not be up for manually adding an extra linker flag via a cargo directive, until 1.8.0 propagates through the distros?
