### ISSUE TITLE
unwind-sys fails to build with RC pkg-config

### ISSUE THREAD

**Issue by DominoTree** [sfackler/rstack#25]
When building with pkg-config `1.7-rc1`, we end up trying to cast the string `7-rc1` to a `u32` here:

https://github.com/sfackler/rstack/blob/master/unwind-sys/build.rs#L16

Simply adding `.replace("-rc","")` seems to work around the issue for now but does screw up the minor version

Might make a PR myself but I haven't looked closely enough to determine the most reasonable way to solve this

**Comment by mrobinson** [comment]
It seems this was fixed in https://github.com/sfackler/rstack/commit/2c991d89c8c80377a71ce5dc99a2609c09bcaeb8, but there hasn't been a new release of `libunwind` or `libunwind-sys` with these changes. Would it be possible to cut a new release with the fixes?

**Comment by sfackler** [comment]
Published!

**Comment by mrobinson** [comment]
@sfackler Thanks very much for the quick release!

**Comment by DominoTree** [comment]
Originally ran into this while building https://github.com/servo/servo - this fix being pushed out will make it a bit easier for new folks to build the app and contribute!
